COLOUR_SOURCE = "RAW" 		# get colour from "JPG" or "RAW"

#Detecting
MIN_THRESHOLD = 80
MAX_THRESHOLD = 255
MIN_NUM_PIXELS = 400
MAX_NUM_PIXELS = 900
MIN_CIRCULARITY = 0.3

MIN_SURROUNDING_CONTRAST = 0

#Pairing
MAX_ANGLE = 30
AVG_RADIUS_MULTIPLIER = 50
MIN_RADIUS_RATIO = 0.5
HU_MOMENT_DISTANCE = 0.2