COLOUR_SOURCE = "RAW" 		# get colour from "JPG" or "RAW"

#Detecting
MIN_THRESHOLD = 150
MAX_THRESHOLD = 255
MIN_NUM_PIXELS = 200
MIN_CIRCULARITY = 0.6

#Pairing
MAX_ANGLE = 30
AVG_RADIUS_MULTIPLIER = 50
MIN_RADIUS_RATIO = 0.8

